version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static/
      - ./media:/var/www/media/
    depends_on:
      - dalalbull
      - dalalbulldaphne

  # auth1:
  #   build: ./excelplay-auth/excelplay_auth/.
  #   depends_on:
  #     - redis
  #     - db
  #   command: bash excelplay-auth/docker_entrypoint.sh
  #   volumes:
  #     - .:/excelplay/excelplay_auth
  #   ports:
  #     - "8000:8000"

  dalalbull:
    build: ./excelplay-dalalbull/excelplay_dalalbull/.
    depends_on:
      - redis
      - db3

    command: bash excelplay-dalalbull/docker_entrypoint.sh

    volumes:
      - .:/excelplay/excelplay_dalalbull
    ports:
      - "8002:8002"

  dalalbulldaphne:
    build: ./excelplay-dalalbull/excelplay_dalalbull/.
    depends_on:
      - dalalbull

    command: bash excelplay-dalalbull/rundaphne.sh
    volumes:
      - .:/excelplay/excelplay_dalalbull
    ports:
      - "8003:8003"

  dalalbullcelery:
    build: ./excelplay-dalalbull/excelplay_dalalbull/.
    depends_on:
      - dalalbull
      - dalalbulldaphne

    command: bash excelplay-dalalbull/runcelery.sh
    volumes:
      - .:/excelplay/excelplay_dalalbull

  # db:
  #   container_name: "db"
  #   restart: always
  #   image: postgres:alpine
  #   expose:
  #     - "5432"
  #   volumes:
  #     - "pgdata:/var/lib/postgresql/data"

  db3:
    container_name: "db3"
    restart: unless-stopped
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    expose:
      - "5434"
    ports:
      - "5434:5432"
    volumes:
      - "pgdatadbull:/var/lib/postgresql/data"

  redis:
    container_name: "redis"
    restart: unless-stopped
    image: redis
    command: redis-server
    volumes:
      - "redisdata:/data"

volumes:
  # pgdata:
  pgdatadbull:
  redisdata:
